Python 3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> input("Int: "
...       if 1 print ("Correct!")
...       
SyntaxError: '(' was never closed
>>> input ("Int: ")
...       
Int: 
''
>>> if int, print ("Correct!")
...       
SyntaxError: invalid syntax
>>> input ("Int?: ") if int print ("Correct!") if False print ("Incorrect!")
...       
SyntaxError: expected 'else' after 'if' expression
>>> input ("Int?: ") if int print ("Correct!") if else print ("Incorrect!")
...       
SyntaxError: expected 'else' after 'if' expression
>>> input ("Int?: ") if int , print ("Correct!") if else print ("Incorrect!")
...       
SyntaxError: expected 'else' after 'if' expression
>>> input("Int?: ") if int print ("Correct!") if else print ("Wrong!")
...       
SyntaxError: expected 'else' after 'if' expression
>>>  input ("int: ") is.digit print ("correct.")
...       
SyntaxError: unexpected indent
>>> input ("int: ") is.digit print ("correct.")
...       
SyntaxError: invalid syntax
>>> Answer = input("Int: ") if answer = int print ("Correct!") if else print ("Wrong!")
...       
SyntaxError: expected 'else' after 'if' expression
>>> Answer = input("Int: ")
...       
Int: 1
>>> if Answer = 1 print ("Correct!")
...       
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
>>> if Answer: 1 print ("_")
...       
SyntaxError: invalid syntax
>>> if answer:1 , print ("_")
... 
...       
Traceback (most recent call last):
  File "<pyshell#15>", line 1, in <module>
    if answer:1 , print ("_")
NameError: name 'answer' is not defined. Did you mean: 'Answer'?
>>> if Answer:1 , print ("_")
... 
...       
_
(1, None)
>>> #I DID IT
...       
>>> if else print ("Wrong!")
...       
SyntaxError: invalid syntax
>>> #Aw no i didnt
...       
