Python 3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> Ans1 = input("Favorite color: ", Ans2 = input ("Favorite artist: ") Ans3 = input ("Favorite game: ")
...              
SyntaxError: invalid syntax. Perhaps you forgot a comma?
>>> Ans1 = input("Favorite color: ", Ans2 =input ("Favorite artist: ") Ans3 =input ("Favorite game: ")
...              
SyntaxError: invalid syntax. Perhaps you forgot a comma?
>>> Ans1 = input("Favorite color: "), Ans2 =input ("Favorite artist: ") Ans3 =input ("Favorite game: ")
...              
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
>>> Ans1= input("Favorite color: ", Ans2 =input ("Favorite artist: ") Ans3 =input ("Favorite game: ")
...             
SyntaxError: invalid syntax. Perhaps you forgot a comma?
>>> Ans1= input("Favorite color: ", Ans2= input ("Favorite artist: ") Ans3= input ("Favorite game: ")
...             
SyntaxError: invalid syntax. Perhaps you forgot a comma?
>>> Ans1 = input("Favorite color: ", Ans2 = input("Favorite artist: ") Ans3 = input("Favorite game: ")
...              
SyntaxError: invalid syntax. Perhaps you forgot a comma?
>>> Ans1 = input("Favorite color: " , Ans2 = input ("Favorite artist: ") , Ans3 = input ("Favorite game: ") , print (f"Summary: {Ans1} , {Ans2} , {Ans3}")
...              
SyntaxError: '(' was never closed
>>> Ans1 = input("Favorite color: ") , Ans2 = input ("Favorite artist: ") , Ans3 = input ("Favorite game: ") , print (f"Summary: {Ans1} , {Ans2} , {Ans3}")
...              
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
>>> Ans1 = input("Favorite color: ")
...              
Favorite color: Green
>>> Ans2 = input("Favorite artist: ")
...              
Favorite artist: KanYe
>>> Ans3 = input("Favorite game: ")
...              
Favorite game: Coconut Simulator
>>> Print (f" Summary: {Ans1} {Ans2} {Ans3}")
...              
Traceback (most recent call last):
  File "<pyshell#27>", line 1, in <module>
    Print (f" Summary: {Ans1} {Ans2} {Ans3}")
NameError: name 'Print' is not defined. Did you mean: 'print'?
>>> print (f" Summary: {Ans1} {Ans2} {Ans3}")
...              
 Summary: Green KanYe Coconut Simulator
>>> #Ah yes the green KanYe Coconut.
...              
>>> print (f" Summary: {Ans1}, {Ans2}, {Ans3},")
...              
 Summary: Green, KanYe, Coconut Simulator,
>>> #yahoo
...              
